In [3]:
import numpy as np

In [8]:
# 4つ揃ったか調べる
def judgement(board,color,x,y):
    win_color = 0
    """
    if board[x, :].sum() == 4 * color \
        or board[:, y].sum() == 4 * color \ #変更点なし
        or (x == y and np.diag(board, k=0).sum() == 4 * color) \
        or (x == 2 - y and np.diag(board[::-1,:], k=0).sum() == 4 * color):
            win_color = color
    return win_color
    """    

In [116]:
def row_color(row_list :list, color :int) -> bool:
    color_count = 0
    for index in range(len(row_list)):
        if row_list[index] == color:
            color_count += 1
        else:
            color_count = 0
        if color_count == 4:
            return True
    return False


In [117]:
#左上から右下
def extract_diag(board, x, y) -> list:
    for i in range(x-1, -1, -1):
        y -= 1

    new_list = np.diag(board, k=y)
    return new_list

In [118]:
#右上から左下
def extract_diag2(board, x, y) -> list:
    for i in range(x, -1, -1):
        if y == 7:
            y += 1
            break
        y += 1
    
    new_list = []
    x = i
    y -= 1

    while(1):
        if x > 5 or y < 0:
            break
        new_list.append(board[x][y])
        x += 1
        y -= 1
    return new_list

In [119]:
tmp_board = [i for i in range(6*8)]
tmp_board =  np.reshape(tmp_board, [6,8])
print(tmp_board[1,:])
new_list = tmp_board[:,1]
#print(new_list)
print(np.diag(tmp_board,k=1))
print(extract_diag(tmp_board,1,1))
print(extract_diag2(tmp_board, 4, 6))
#print(tmp_board)

[ 8  9 10 11 12 13 14 15]
[ 1 10 19 28 37 46]
[ 0  9 18 27 36 45]
[31, 38, 45]


In [109]:
def judgement2(board,color,x,y):
    win_color = 0
    if row_color(board[x, :], color) \
        or board[:, y].sum() == 4 * color \
        or row_color(extract_diag(board, x, y),color) \
        or row_color(extract_diag2(board, x, y),color):
            win_color = color
    return win_color

In [112]:
board = np.zeros((6,8))

board[5][3]=1
board[4][4]=1
board[3][5]=1
board[2][6]=1

print(judgement2(board, 1, 4, 4))

1


In [14]:
print(tmp_board[:,3]) #横一列

[ 3 11 19 27 35 43]


In [25]:
board = np.zeros((6,8))

In [26]:
board[5][3]=1
board[4][4]=1
board[3][5]=1
board[2][6]=1
board

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]])

In [23]:
judgement(board,1,2,6)

0

In [75]:
x = 5
y = 0
for i in range(7):
    if 

ValueError: Input must be 1- or 2-d.

In [2]:
BLACK, WHITE  = 1, -1
class State_6_8_4:
    '''○×ゲームの盤面実装'''
    X, Y = 'ABCDEF',  '12345678'
    C = {0: '_', BLACK: 'O', WHITE: 'X'}

    def __init__(self):
        self.board = np.zeros((6, 8)) # (x, y)
        self.color = 1
        self.win_color = 0
        self.record = []
        self.reverse_num = 0
        self.round = 0
    
    def get_board(self):
       return self.board

    def action2str(self, a):
        return self.X[a // 8] + self.Y[a % 8]

    def str2action(self, s):
        return self.X.find(s[0]) * 8 + self.Y.find(s[1])

    def record_string(self):
        return ' '.join([self.action2str(a) for a in self.record])

    def __str__(self):
        # 表示
        s = '   ' + ' '.join(self.Y) + '\n'
        for i in range(6):
            s += self.X[i] + ' ' + ' '.join([self.C[self.board[i, j]] for j in range(8)]) + '\n'
        s += 'record = ' + self.record_string()
        return s
    
    def row_color(row_list :list, color :int) -> bool:
        color_count = 0
        for index in range(len(row_list)):
            if row_list[index] == color:
                color_count += 1
            else:
                color_count = 0
            if color_count == 4:
                return True
        return False

    #左上から右下
    def extract_diag(self, x, y) -> list:
        for i in range(x-1, -1, -1):
            y -= 1
        new_list = np.diag(self.board, k=y)
        return new_list
    
    #右上から左下
    def extract_diag2(self, x, y) -> list:
        for i in range(x, -1, -1):
            if y == 7:
                y += 1
                break
            y += 1
    
        new_list = []
        x = i
        y -= 1

        while(1):
            if x > 5 or y < 0:
                break
            new_list.append(self.board[x][y])
            x += 1
            y -= 1
        return new_list

    def play(self, action, net, state):
        # 行動で状態を進める関数
        # action は board 上の位置 (0 ~ 8) または行動系列の文字列
        if isinstance(action, str):
            for astr in action.split():
                self.play(self.str2action(astr))
            return self

        x, y = action // 8, action % 8
        self.board[x, y] = self.color

        """
        # 4つ揃ったか調べる
        if self.board[x, :].sum() == 4 * self.color \
          or self.board[:, y].sum() == 4 * self.color \
          or (x == y and np.diag(self.board, k=0).sum() == 4 * self.color) \
          or (x == 2 - y and np.diag(self.board[::-1,:], k=0).sum() == 4 * self.color):
            self.win_color = self.color
        """
        #4つ揃ったか調べる
        if self.row_color(self.board[x, :], self.color) \
            or self.board[:, y].sum() == 4 * self.color \
            or self.row_color(self.extract_diag(self.board, x, y),self.color) \
            or self.row_color(self.extract_diag2(self.board, x, y),self.color):
                self.win_color = self.color
        
        print("round: " + str(self.round))
        if self.jadge(net, state) and self.reverse_num < 3:
           #if self.jadge(net, state):
              self.reverse()
              self.reverse_num += 1

        self.color = -self.color
        self.record.append(action)
        self.round += 1
        return self

    def terminal(self):
        # 終端状態かどうか返す
        return self.win_color != 0 or len(self.record) == 6 * 8

    def terminal_reward(self):
        # 終端状態での勝敗による報酬を返す
        return self.win_color if self.color == BLACK else -self.win_color

    ##############################################################
    def legal_actions(self): #コードを変更
        # 可能な行動リストを返す
        vaild_pos = []
        for col in range(8):
           for row in range(5, -1, -1):
              if self.board[row, col] == 0:
                 vaild_pos.append(row*8+col)
                 break
        return vaild_pos
        #return [a for a in range(6 * 8) if self.board[a // 8, a % 8] == 0]

    def feature(self):
        # ニューラルネットに入力する状態表現を返す
        return np.stack([self.board == self.color, self.board == -self.color]).astype(np.float32)
    
    ##################################################
    def jadge(self, net, state) -> bool:  #コードを書き加える
      p, v = net.predict(state)
      pt_upper_limit = 0.7 #上限 
      pt_lower_limit = 0.6 #下限

      if pt_lower_limit <= v <= pt_upper_limit:
         return True 
      else:
         return False
      
    def reverse(self):
       for col in range(8):
          for row in range(5, -1, -1):
            if self.board[row][col] != 0:
              self.board[row][col] *= -1
            else:
               break


In [ ]:
state = State_6_8_4()